### ISSUE TITLE
GB filter shows no results.

### ISSUE THREAD

**Issue by NaughtyOttsel** [RichardHpa/Pokemon-TCG-Standings#42]
When trying to view the results for players from the UK using the filters (GB 🇬🇧) no results are returned; 

I believe this is because the players are being displayed with the `[UK]` country and so the filter is not working.

When trying to change the URL to use UK you are redirected to a 404 Page Not Found

**Comment by RichardHpa** [comment]
Good catch. Sorry I didnt see this earlier. Spent most of the weekend trying to find solutions to the api issues.

I took the initial Competitors list from https://worlds.pokemon.com/en-us/in-person/competitors/ which uses GB but it seems RK9 uses UK so that makes sense why that filter wasnt working.

Even though worlds has finished il make sure to fix this for the page
